### PR TITLE
Properly write and read signals

### PR DESCRIPTION
**Pull request by rageandqq**
There were a few issues in how we were writing, and more importantly, reading the signals:

- signal sign-edness was not respected. This fixes it, by properly setting the MSB for signed values
- **most important**: enddiannes was not respected, and the way we were reading signals was wrong.

Take a look at the blue signal for Voltage in this image:
vectormsgdef
The `start_bit` is 19, and the `length` of the message is 15 bits.

Previously, if our message was stored in the 64 bit string `msg`, we would have used:
`msg[19+15 .. 19]` in MSB to LSB order. However, this doesn't make sense, because if you visually look at the signal, the MSB to LSB ordered number should be: `msg[1], msg[0], msg[15 .. 8], msg[23 .. 19]`, since this message is stored in big endian format.

This PR fixes this issue. I tried to leave comments in explaining the logic when necessary. Essentially, anytime we need to move to the "next byte", I move to the start of the previous byte and start reading the next 8 bits from it, since the LSB is the first byte and the MSB is the last byte.
I confirmed that the same value output by the writer script is read in the reader script.
I'll be confirming that this works with the actual car as well, and updating this PR if needed.

I also added the remaining signals/messages we need to the `messages.json` file.

### CODE REVIEW

**Comment by rageandqq** [comment]
@matraj not according to the "source of truth" spreadsheet we have.
https://docs.google.com/spreadsheets/d/19GecFn-wkvSvXLGU-021cpQsl9yt6vDFgqbNWHS24yY/edit#gid=0

**Comment by rageandqq** [comment]
Thanks @jack-mo ! Sorry for not looping you in before on the last few PRs, we were just focussing on getting stuff out, and GitHub auto-recommended that we do on this one :)

I have been trying to keep all the code readable, and documenting all motivation in PRs. Hope that it's easy enough for future maintainers to pick up!

**Comment by jack-mo** [comment]
Haha, it's all good. I'm going to update some dependencies, apparently our version of Electron has a security vulnerability 😬

**Comment by brandonwalton** [comment]
If you have control over this message's layout I would highly recommend you move the MSB of hvbatt_voltage to start on byte 1 instead of spreading the signal across three bytes.

**Pull request merged**
